### ISSUE TITLE
Students plagiarizing your work

### ISSUE THREAD

**Issue by mwood7** [JanisErdmanis/PythonPhysics#1]
Good day Dr. Erdmanis:

I'm Matt Wood (Matt.wood@tamuc.edu), professor of physics and astronomy at Texas A&M University-Commerce.  I teach computational physics using Newman's book, and I'm afraid I continually have a problem that students find your site and copy/paste your solutions as their own.  Often they obfuscate the code, but sometimes not at all.  

It is too much to ask, but for my own sake, and those many others who are also teaching from Newman and dealing with students being lazy, would you consider hiding this repository so students cannot find it so easily?  I believe it is important for students to wrestle with the code and to do their own work, and while I know there are other places they can find solutions online, none are quite so easy to navigate as yours.

Again, I know it is too much to ask, and I don't expect you to actually do it, but I thought I would ask.

FWIW, I did a sabbatical at Radboud U in The Netherlands about a decade ago.  I just loved everything about it.

Cheers,
Matt

--
Matt A Wood
Regents Professor of Physics & Astronomy 
Texas A&M University-Commerce
Commerce, TX 75429

**Comment by JanisErdmanis** [comment]
Dear Prof. Wood

When I first shared my Python solutions, it was never my intention for them to be a source of plagiarism. I did so to showcase my competencies, which played a significant role in my successful applications to the CERN summer school and my PhD program. 

I am not ready to make the repository private as it still serves as a display of my competencies in Python. Also it is a good reference showing obscurity of the Pyhton language for numerical computing. Instead, I address the issue of display:

- I have removed the repository description referencing the discussed book in question
- I have changed the repo name to `PythonPhysics` so it would not be easy to find by book title

Both of these changes retract references to the book, and thus, in the future, when search engines do reindex, it will be harder for students to find this repo. 

I suggest using Julia for the coursework, as that would make this repo irrelevant, and those who find this repo and would want to plagiarise would be forced to learn Python on top of that.

**Comment by mwood7** [comment]
Dr. Erdmanis:

Good morning, and thank you so much for your quick reply.  I appreciate so very much the steps you have taken to make it less easy for students to find your repository!  I fully understand you wanting to keep it public as it is a very tangible demonstration of your Python skills.

I haven’t done any programming in Julia, but your suggestion prompts me to at least spend a few hours exploring it.

Cheers, and thank you again,
Matt

**Comment by JanisErdmanis** [comment]
Ok. Then I close the issue.
